# -*- coding: utf-8 -*-
"""Pl@ntnet_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNFetm5j04o-i7Y-Psu3CKaBmuAGnSba
"""

import requests
import json
from pprint import pprint

API_KEY = "2b10u90x0upUVflyspMrtBnrye"  # Set you API_KEY here
PROJECT = "all" # try "weurope" or "canada"
api_endpoint = f"https://my-api.plantnet.org/v2/identify/{PROJECT}?api-key={API_KEY}"


image_path_1 = "image7.jpeg"
image_data_1 = open(image_path_1, 'rb')

image_path_2 = "image8.jpeg"
image_data_2 = open(image_path_2, 'rb')


data = {
    'organs': ['auto', 'auto']
}

files = [
    ('images', (image_path_1, image_data_1)),
    ('images', (image_path_2, image_data_2))
]

req = requests.Request('POST', url=api_endpoint, files=files, data=data)
prepared = req.prepare()

s = requests.Session()
response = s.send(prepared)
json_result = json.loads(response.text)

pprint(response.status_code)
#pprint(json_result)
count = 10
print(json_result['bestMatch'])
for result in json_result['results']:
  if (count > 1):
    scientific_name = result['species']['scientificName']
    score = result['score']
    var = scientific_name + " " + str(score)
    print(var)
    count = count - 1

